### ISSUE TITLE
项目功能

### ISSUE THREAD

**Issue by ehaoxiongdiycw** [jiansiting/WPA2-KRACK#1]
这个攻击能实现任意 wifi 中间人攻击吗？

**Comment by thehappydinoa** [comment]
该程序可用于测试您的WiFi的漏洞。 对不起我可怜的普通话

**Comment by 0xsunsama** [comment]
这个与krack官方视频中所演示的效果一样吗？最终能达到什么效果？thk

**Comment by thehappydinoa** [comment]
@ChildeSun 这使用krack并测试您的计算机的漏洞
